using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

// <copyright file="PathStringTest.IsAbsoluteUrl.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>

namespace SaveScumAgent.Tests
{
    public partial class PathStringTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof (PathStringTest))]
        public void IsAbsoluteUrl_ReturnsFalseForEmptyString()
        {
            PathString s0 = new PathString("");
            Assert.IsFalse(IsAbsoluteUrl(s0));
        }
        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        public void IsAbsoluteUrl_ReturnsFalseForNullString()
        {
            PathString s0 = new PathString(null);
            Assert.IsFalse(IsAbsoluteUrl(s0));
        }

        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        public void IsAbsoluteUrl_ReturnsFalseForRelativePath()
        {
            PathString s0 = new PathString(@".\stuff.txt");
            Assert.IsFalse(IsAbsoluteUrl(s0));
        }

        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        public void IsAbsoluteUrl_ReturnsTrueForAbsolutePath()
        {
            PathString s0 = new PathString(@"c:\stuff.txt");
            Assert.IsTrue(IsAbsoluteUrl(s0));
        }
    }
}