using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

// <copyright file="PathStringTest.IsFolderSubfolderOf.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>

namespace SaveScumAgent.Tests
{
    public partial class PathStringTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof (PathStringTest))]
        public void IsFolderSubfolderOf431()
        {
            bool b;
            b = IsFolderSubfolderOf(null, null);
            Assert.AreEqual(false, b);
        }
    }
}
