using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

// <copyright file="PathStringTest.IsFolderSubfolderOf01.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>

namespace SaveScumAgent.Tests
{
    public partial class PathStringTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof (PathStringTest))]
        [ExpectedException(typeof (ArgumentException))]
        public void IsFolderSubfolderOf01ThrowsArgumentException_WhenPossibleParentIsRelative()
        {
            bool b;
            PathString s0 = new PathString("some.junk");
            b = IsFolderSubfolderOf01(s0, @"..\relative_path");
        }

        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        public void IsFolderSubfolderOf_ReturnsTrueOnRelativePath()
        {
            var s0 = new PathString("some.junk");
            var b = IsFolderSubfolderOf01(s0, @"c:\relative_path");
            Assert.IsTrue(b);
        }
        

        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        public void IsFolderSubfolderOf_ReturnsTrueWhenPossibleParentPathIsParent()
        {
            var s0 = new PathString(@"c:\parent_path\some.junk");
            var b = IsFolderSubfolderOf01(s0, @"c:\parent_path");
            Assert.IsTrue(b);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        public void IsFolderSubfolderOf_ReturnsTrueWhenPossibleParentPathIsSlashedParent()
        {
            var s0 = new PathString(@"c:\parent_path\some.junk");
            var b = IsFolderSubfolderOf01(s0, @"c:\parent_path\");
            Assert.IsTrue(b);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        public void IsFolderSubfolderOf_ReturnsTrueWhenPossibleParentPathIsInSubfolderOfParent()
        {
            var s0 = new PathString(@"c:\parent_path\sub_parent\some.junk");
            var b = IsFolderSubfolderOf01(s0, @"c:\parent_path");
            Assert.IsTrue(b);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        public void IsFolderSubfolderOf_ReturnsFalseWhenPossibleParentPathIsInSubfolderOfWrongParent()
        {
            var s0 = new PathString(@"c:\parent_path\sub_parent\some.junk");
            var b = IsFolderSubfolderOf01(s0, @"c:\different_path");
            Assert.IsFalse(b);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        public void IsFolderSubfolderOf_ReturnsFalseWhenPossibleParentPathIsNotParent()
        {
            var s0 = new PathString(@"c:\parent_path\some.junk");
            var b = IsFolderSubfolderOf01(s0, @"c:\different_path");
            Assert.IsFalse(b);
        }
    }
}