using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

// <copyright file="PathStringTest.GetRelativePathFromAbsolute.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>

namespace SaveScumAgent.Tests
{
    public partial class PathStringTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof (PathStringTest))]
        [ExpectedException(typeof (InvalidOperationException))]
        public void GetRelativePathFromAbsoluteThrowsInvalidOperationException940()
        {
            string s;
            PathString s0 = new PathString((string) null);
            s = GetRelativePathFromAbsolute(s0, null);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        [ExpectedException(typeof(ArgumentException))]
        public void GetRelativePathFromAbsolute_ThrowsArgumentExceptionForEmptyBasePath()
        {
            string s;
            PathString s0 = new PathString(@"c:\junk\stuff.text");
            s = GetRelativePathFromAbsolute(s0, "");
        }

        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        public void GetRelativePathFromAbsolute_ReturnsOnlyFilenameWithParentPath()
        {
            string s;
            PathString s0 = new PathString(@"c:\junk\stuff.text");
            s = GetRelativePathFromAbsolute(s0, @"c:\junk\");
            Assert.AreEqual("stuff.text", s);
        }

        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        public void GetRelativePathFromAbsolute_ReturnsOnlyFilenameWithNoTailingSlashParentPath()
        {
            var s0 = new PathString(@"c:\junk\stuff.text");
            var s = GetRelativePathFromAbsolute(s0, @"c:\junk");
            Assert.AreEqual("stuff.text", s);
        }
        [TestMethod]
        [PexGeneratedBy(typeof(PathStringTest))]
        public void GetRelativePathFromAbsolute_ReturnsFilenameAndSubParentFromSubfolderOfBasePath()
        {
            var s0 = new PathString(@"c:\junk\stuff.text");
            var s = GetRelativePathFromAbsolute(s0, @"c:\");
            Assert.AreEqual(@"junk/stuff.text", s);
        }
    }
}
