using System;
using System.IO;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SevenZip;
// <copyright file="SaveGameAgentTest.Constructor.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>

namespace AutoBackup
{
    public partial class SaveGameAgentTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof (SaveGameAgentTest))]
        [ExpectedException(typeof (ArgumentNullException))]
        public void ConstructorThrowsArgumentNullException812()
        {
            var saveAgent = Constructor(null, null,
                0, OutArchiveFormat.SevenZip, CompressionLevel.None);
        }

        [TestMethod]
        [PexGeneratedBy(typeof (SaveGameAgentTest))]
        [ExpectedException(typeof(ArgumentException))]
        public void RejectsZeroInterval()
        {
            var subfolder = Path.GetTempPath();
            var folder = new DirectoryInfo(subfolder).Parent.FullName;

            var saveAgent = Constructor(subfolder, folder,
                0, OutArchiveFormat.SevenZip, CompressionLevel.None);
        }

        [TestMethod]
        [PexGeneratedBy(typeof (SaveGameAgentTest))]
        public void UpdatesFilesystemDeayEvent()
        {
            var subfolder = Path.GetTempPath();
            var folder = new DirectoryInfo(subfolder).Parent.FullName;

            var saveAgent = Constructor(subfolder, folder,
                1, OutArchiveFormat.SevenZip, CompressionLevel.None);

            Assert.AreEqual(1, saveAgent.WatchEventDelay);
            saveAgent.WatchEventDelay = 10;
            Assert.AreEqual(10, saveAgent.WatchEventDelay);
        }

        [TestMethod]
        [PexGeneratedBy(typeof (SaveGameAgentTest))]
        [ExpectedException(typeof (ArgumentException))]
        public void ThrowsExceptionWhenArchiveFolderIsSubfolderOfWatchFolder()
        {
            SaveAgent saveAgent;

            var subfolder = Path.GetTempPath();
            var folder = new DirectoryInfo(subfolder).Parent.FullName;

            saveAgent = Constructor(folder, subfolder,
                1, OutArchiveFormat.SevenZip, CompressionLevel.None);
        }

        [TestMethod]
        [PexGeneratedBy(typeof (SaveGameAgentTest))]
        [ExpectedException(typeof (ArgumentNullException))]
        public void ConstructorThrowsArgumentNullException676()
        {
            SaveAgent saveAgent;
            saveAgent = Constructor(null, null,
                0, OutArchiveFormat.SevenZip, CompressionLevel.None);
        }
    }
}