//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace AutoBackup.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("archives")]
        public string ArchivesFolder {
            get {
                return ((string)(this["ArchivesFolder"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int GamesToKeep {
            get {
                return ((int)(this["GamesToKeep"]));
            }
            set {
                this["GamesToKeep"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int DelayInSeconds {
            get {
                return ((int)(this["DelayInSeconds"]));
            }
            set {
                this["DelayInSeconds"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [SpecialSetting(SpecialSetting.ConnectionString)]
        [DefaultSettingValue("data source=\"C:\\Users\\drspacemonkey\\Documents\\Visual Studio 2013\\Projects\\AutoBac" +
            "kup\\AutoBackup\\BackupMetadata.sqlite\"")]
        public string BackupMetadataConnectionString {
            get {
                return ((string)(this["BackupMetadataConnectionString"]));
            }
        }
    }
}
