using System.Text;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="GitWrapperTest.CloneRepo.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;
using System.IO;
using LibGit2Sharp;

namespace SavegameAutoBackupAgent
{
    public partial class GitWrapperTest
    {
/*        [TestMethod]
        [PexGeneratedBy(typeof (GitWrapperTest))]
        public void CheckoutRepoTest()
        {
            var profilesFolder = GitWrapper.ProfilesFolder;

            var s = this.CloneRepo(profilesFolder, Properties.Settings.Default.ProfilesRepo, true);

            Assert.IsTrue(s);
        }*/


        [TestMethod]
        [PexGeneratedBy(typeof (GitWrapperTest))]
        [ExpectedException(typeof (ArgumentNullException))]
        public void CloneRepoThrowsArgumentNullException477()
        {
            var s = this.CloneRepo((string) null, (string) null, false);
        }
    }
}