using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="GitWrapperTest.CloneProfilesRepo.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;
using LibGit2Sharp;

namespace SavegameAutoBackupAgent
{
    public partial class GitWrapperTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof (GitWrapperTest))]
        public void GitWrapperUpdatesProfileRepo()
        {
            GitWrapper.ForceDeleteDirectory(GitWrapper.ProfilesFolder);
            var b = GitWrapper.CloneProfilesRepo();
            Assert.AreEqual(typeof(Repository), new Repository(b).GetType());
        }
    }
}