using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="GitWrapperTest.CheckRepoStatus.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace SavegameAutoBackupAgent
{
    public partial class GitWrapperTest
    {
        [TestMethod]
        [PexGeneratedBy(typeof (GitWrapperTest))]
        public void CheckRepoStatusAgainstRemoteThrowsArgumentNullException35()
        {
            object o;
            o = this.CheckRepoStatusAgainstRemote("test");
            Assert.IsNull(o);
        }
[TestMethod]
[PexGeneratedBy(typeof(GitWrapperTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void CheckRepoStatusAgainstRemoteThrowsArgumentNullException805()
{
    object o;
    o = this.CheckRepoStatusAgainstRemote((string)null);
}
    }
}
