using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <copyright file="GitWrapperTest.GetGitFolder.g.cs">Copyright ©  2015</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace SavegameAutoBackupAgent
{
    public partial class GitWrapperTest
    {
[TestMethod]
[PexGeneratedBy(typeof(GitWrapperTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetGitFolderThrowsArgumentNullException454()
{
    string s;
    s = this.GetGitFolder((string)null);
}
    }
}
