//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SavegameAutoBackupAgent.DatabaseTools
{
    using System;
    
    public enum CullType : int
    {
        SevenZip = 0,
        ShadowCopy = 1,
        SymlinkSnapshot = 2,
        Zip = 3
    }
}
