//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBackup.DatabaseTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangedFile
    {
        public int Id { get; set; }
        public string Filename { get; set; }
        public string MD5 { get; set; }
        public int Size { get; set; }
    
        public virtual Archive Archive { get; set; }
    }
}
