//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBackup.DatabaseTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.IsDefault = false;
            this.Archives = new HashSet<Archive>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string FilesafeTitle { get; set; }
        public Nullable<int> MaxKept { get; set; }
        public string WatchFolder { get; set; }
        public string ArchiveFolder { get; set; }
        public CullType CullType { get; set; }
        public Nullable<bool> CalculateChecksums { get; set; }
        public bool IsDefault { get; private set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual ICollection<Archive> Archives { get; set; }
    }
}
